/* Hindi for the PakkaBill Meesho P&L (pnl.html). English is the default; this file turns every
   label, note and message into Hindi when the seller picks हिंदी. Keys are the English text with
   numbers written as {n} and dates as {d}; in the Hindi text {n} and {d} are filled in the same
   order ({n2} picks the second number, {d1} the first date, when Hindi needs a different order).
   Text not found here (SKU codes, product and file names) stays as it is. */
(function () {
  'use strict';
  var D = {
    /* chrome, tabs, language */
    'Hisaab': 'हिसाब',
    'Meesho P&L and reconciliation': 'Meesho मुनाफ़ा-नुकसान और मिलान',
    'Sections': 'हिस्से',
    'P&L': 'मुनाफ़ा-नुकसान',
    'Reconcile': 'मिलान',
    'Upload': 'अपलोड',
    'Costs': 'लागत',
    'Expenses': 'खर्च',
    'Settings': 'सेटिंग्स',
    'How to use': 'कैसे इस्तेमाल करें',
    'Language': 'भाषा',
    'Language of the P&L tool': 'P&L टूल की भाषा',
    'Everything in this tool, including notes and messages, changes to the language you pick. Your choice is remembered on this device.': 'इस टूल की हर चीज़, नोट और मैसेज समेत, आपकी चुनी भाषा में दिखेगी। आपकी पसंद इस डिवाइस पर याद रहती है।',
    '{n} missing': '{n} बाकी',
    '{n} need attention': '{n} पर ध्यान दें',

    /* hero */
    'PakkaBill Profit & Loss': 'PakkaBill मुनाफ़ा-नुकसान',
    'Know your real profit': 'अपना असली मुनाफ़ा जानिए',
    'Every Meesho fee, return, RTO, GST and product cost taken out. Reconciled to the paisa.': 'Meesho की हर फ़ीस, रिटर्न, RTO, GST और प्रोडक्ट की लागत घटाकर। पैसे-पैसे का मिलान।',
    'Not just sales. Every Meesho fee, return, RTO, GST and product cost taken out, reconciled to the paisa.': 'सिर्फ़ बिक्री नहीं। Meesho की हर फ़ीस, रिटर्न, RTO, GST और प्रोडक्ट की लागत घटाकर, पैसे-पैसे का मिलान।',
    'Real profit': 'असली मुनाफ़ा',
    'Real loss': 'असली नुकसान',
    '{n} margin': '{n} मार्जिन',
    '{n} of what you sold': 'बिक्री का {n}',
    '{n} of what you sold · {d} to {d}': 'बिक्री का {n} · {d} से {d}',
    'See your real profit in {n} minutes': '{n} मिनट में अपना असली मुनाफ़ा देखें',
    'Upload files': 'फ़ाइलें अपलोड करें',
    'Try with sample data': 'सैंपल डेटा से देखें',

    /* next steps */
    'Your next steps': 'आपके अगले कदम',
    '{n} of {n} done': '{n2} में से {n1} पूरे',
    '{n} step left for an exact profit': 'सही मुनाफ़े के लिए {n} कदम बाकी',
    '{n} steps left for an exact profit': 'सही मुनाफ़े के लिए {n} कदम बाकी',
    'You are all set. One optional step is left.': 'सब तैयार है। बस एक कदम बाकी है, वह भी ज़रूरी नहीं।',
    'Hide': 'छिपाएँ',
    'Hide next steps': 'अगले कदम छिपाएँ',
    'Optional': 'ज़रूरी नहीं',
    'Done': 'पूरा',
    'Add the Meesho payment report': 'Meesho की पेमेंट रिपोर्ट जोड़ें',
    'Profit is worked out from it.': 'मुनाफ़ा इसी से निकलता है।',
    'Payment report added': 'पेमेंट रिपोर्ट जुड़ गई',
    'Add product cost for {n} SKUs': '{n} SKU की प्रोडक्ट लागत भरें',
    'Add product cost for {n} SKU': '{n} SKU की प्रोडक्ट लागत भरें',
    'Without costs, profit looks higher than it really is.': 'लागत के बिना मुनाफ़ा असल से ज़्यादा दिखता है।',
    'Product costs added': 'प्रोडक्ट की लागत भर दी',
    'Check {n} returns: resellable or not': '{n} रिटर्न देखें: दोबारा बिकने लायक हैं या नहीं',
    'Check {n} return: resellable or not': '{n} रिटर्न देखें: दोबारा बिकने लायक है या नहीं',
    'Mark items that came back damaged, so your stock cost is right.': 'जो सामान खराब लौटा, उसे मार्क करें ताकि स्टॉक की लागत सही रहे।',
    'Returns checked': 'रिटर्न देख लिए',
    'Add other costs like packing, rent or staff': 'पैकिंग, किराया या स्टाफ़ जैसे दूसरे खर्च जोड़ें',
    'Add other costs like packing, rent or staff (optional)': 'पैकिंग, किराया या स्टाफ़ जैसे दूसरे खर्च जोड़ें (ज़रूरी नहीं)',
    'Costs outside Meesho, spread over the month.': 'Meesho के बाहर के खर्च, पूरे महीने में बाँटे जाते हैं।',
    'Other costs added': 'दूसरे खर्च जुड़ गए',
    'Download your P&L report': 'अपनी P&L रिपोर्ट डाउनलोड करें',
    'Download your P&L report (PDF or Excel)': 'अपनी P&L रिपोर्ट डाउनलोड करें (PDF या Excel)',
    'PDF or Excel, to keep or to share with your CA.': 'PDF या Excel, रखने के लिए या अपने CA को भेजने के लिए।',
    'Report downloaded': 'रिपोर्ट डाउनलोड हो गई',
    'Add costs': 'लागत भरें',
    'Check': 'देखें',
    'Add': 'जोड़ें',

    /* period and downloads */
    'Period': 'समय',
    'All data': 'पूरा डेटा',
    'Custom dates': 'अपनी तारीखें',
    'From': 'से',
    'To': 'तक',
    'Count sales by': 'बिक्री किस तारीख से गिनें',
    'Payment date': 'पेमेंट की तारीख',
    'Order date': 'ऑर्डर की तारीख',
    'Download Excel': 'Excel डाउनलोड करें',
    'Download PDF': 'PDF डाउनलोड करें',
    'Share on WhatsApp': 'WhatsApp पर भेजें',
    '{d} to {d}': '{d} से {d}',

    /* summary */
    'Summary': 'सारांश',
    'Net profit': 'शुद्ध मुनाफ़ा',
    'Net sales': 'नेट बिक्री',
    'Received from Meesho': 'Meesho से मिला',
    'Orders sold': 'बिके ऑर्डर',
    'RTO · Return · Exchange': 'RTO · रिटर्न · एक्सचेंज',
    '{n} of net revenue': 'नेट आमदनी का {n}',
    '▲ {n} more than {d}': '▲ {d} से {n} ज़्यादा',
    '▼ {n} less than {d}': '▼ {d} से {n} कम',
    'Same as {d}': '{d} जितना ही',

    /* notes */
    'Add the payment report to see profit. The orders report alone has no settlement amounts.': 'मुनाफ़ा देखने के लिए पेमेंट रिपोर्ट जोड़ें। सिर्फ़ ऑर्डर रिपोर्ट में सेटलमेंट की रकम नहीं होती।',
    'Cost is missing for {n} SKUs ({n} pieces). Profit is overstated until you add them.': '{n} SKU ({n} पीस) की लागत नहीं भरी है। जब तक नहीं भरेंगे, मुनाफ़ा ज़्यादा दिखेगा।',
    'Cost is missing for {n} SKU ({n} pieces). Profit is overstated until you add them.': '{n} SKU ({n} पीस) की लागत नहीं भरी है। जब तक नहीं भरेंगे, मुनाफ़ा ज़्यादा दिखेगा।',
    'Cost is missing for {n} SKU ({n} piece). Profit is overstated until you add them.': '{n} SKU ({n} पीस) की लागत नहीं भरी है। जब तक नहीं भरेंगे, मुनाफ़ा ज़्यादा दिखेगा।',
    'Review returns': 'रिटर्न देखें',
    '{n} returns and RTO parcels are counted as back in stock, so their cost goes back to your stock. If any came back damaged, used or wrong, mark it Not resellable in Reconcile.': '{n} रिटर्न और RTO पार्सल वापस स्टॉक में गिने गए हैं, इसलिए उनकी लागत स्टॉक में लौट जाती है। जो सामान खराब, इस्तेमाल किया हुआ या गलत लौटा हो, उसे मिलान में "दोबारा बिकने लायक नहीं" मार्क करें।',
    '{n} orders show as returned or RTO, but Meesho has not reversed the sale in these files yet ({n} of sales). Profit will drop when that reversal is paid out.': '{n} ऑर्डर रिटर्न या RTO दिख रहे हैं, पर Meesho ने इन फ़ाइलों में अभी बिक्री वापस नहीं काटी है ({n} की बिक्री)। जब यह कटेगी, मुनाफ़ा घटेगा।',
    '{n} order shows as returned or RTO, but Meesho has not reversed the sale in these files yet ({n} of sales). Profit will drop when that reversal is paid out.': '{n} ऑर्डर रिटर्न या RTO दिख रहा है, पर Meesho ने इन फ़ाइलों में अभी बिक्री वापस नहीं काटी है ({n} की बिक्री)। जब यह कटेगी, मुनाफ़ा घटेगा।',
    '{n} settlement row does not fully add up from Meesho’s own columns: Meesho paid {n} less than they add up to. The difference is shown as its own line, so the total still matches Meesho.': '{n} सेटलमेंट लाइन Meesho के अपने कॉलम से पूरी नहीं जुड़ती: Meesho ने जोड़ से {n} कम दिए। यह फ़र्क अलग लाइन में दिखाया है, ताकि कुल रकम Meesho से मिलती रहे।',
    '{n} settlement row does not fully add up from Meesho’s own columns: Meesho paid {n} more than they add up to. The difference is shown as its own line, so the total still matches Meesho.': '{n} सेटलमेंट लाइन Meesho के अपने कॉलम से पूरी नहीं जुड़ती: Meesho ने जोड़ से {n} ज़्यादा दिए। यह फ़र्क अलग लाइन में दिखाया है, ताकि कुल रकम Meesho से मिलती रहे।',
    '{n} settlement rows do not fully add up from Meesho’s own columns: Meesho paid {n} less than they add up to. The difference is shown as its own line, so the total still matches Meesho.': '{n} सेटलमेंट लाइनें Meesho के अपने कॉलम से पूरी नहीं जुड़तीं: Meesho ने जोड़ से {n} कम दिए। यह फ़र्क अलग लाइन में दिखाया है, ताकि कुल रकम Meesho से मिलती रहे।',
    '{n} settlement rows do not fully add up from Meesho’s own columns: Meesho paid {n} more than they add up to. The difference is shown as its own line, so the total still matches Meesho.': '{n} सेटलमेंट लाइनें Meesho के अपने कॉलम से पूरी नहीं जुड़तीं: Meesho ने जोड़ से {n} ज़्यादा दिए। यह फ़र्क अलग लाइन में दिखाया है, ताकि कुल रकम Meesho से मिलती रहे।',

    /* lock */
    'Full report locked': 'पूरी रिपोर्ट लॉक है',
    'See your full report': 'अपनी पूरी रिपोर्ट देखें',
    'Reconcile every order': 'हर ऑर्डर का मिलान करें',
    'Log in or create a free account, then get PakkaBill Pro to open the complete profit and loss report.': 'लॉग इन करें या मुफ़्त अकाउंट बनाएँ, फिर पूरी मुनाफ़ा-नुकसान रिपोर्ट खोलने के लिए PakkaBill Pro लें।',
    'Log in or create a free account, then get PakkaBill Pro to open the complete profit and loss report. New accounts get {n} days of Pro free.': 'लॉग इन करें या मुफ़्त अकाउंट बनाएँ, फिर पूरी मुनाफ़ा-नुकसान रिपोर्ट खोलने के लिए PakkaBill Pro लें। नए अकाउंट को {n} दिन Pro मुफ़्त मिलता है।',
    'Log in or create a free account, then get PakkaBill Pro to open order-by-order reconciliation.': 'लॉग इन करें या मुफ़्त अकाउंट बनाएँ, फिर हर ऑर्डर का मिलान खोलने के लिए PakkaBill Pro लें।',
    'Log in or create a free account, then get PakkaBill Pro to open order-by-order reconciliation. New accounts get {n} days of Pro free.': 'लॉग इन करें या मुफ़्त अकाउंट बनाएँ, फिर हर ऑर्डर का मिलान खोलने के लिए PakkaBill Pro लें। नए अकाउंट को {n} दिन Pro मुफ़्त मिलता है।',
    'get PakkaBill Pro to open the complete profit and loss report.': 'पूरी मुनाफ़ा-नुकसान रिपोर्ट खोलने के लिए PakkaBill Pro लें।',
    'Get PakkaBill Pro to open the complete profit and loss report.': 'पूरी मुनाफ़ा-नुकसान रिपोर्ट खोलने के लिए PakkaBill Pro लें।',
    'Get PakkaBill Pro to open the complete profit and loss report. New accounts get {n} days of Pro free.': 'पूरी मुनाफ़ा-नुकसान रिपोर्ट खोलने के लिए PakkaBill Pro लें। नए अकाउंट को {n} दिन Pro मुफ़्त मिलता है।',
    'Get PakkaBill Pro to open order-by-order reconciliation.': 'हर ऑर्डर का मिलान खोलने के लिए PakkaBill Pro लें।',
    'Get PakkaBill Pro to open order-by-order reconciliation. New accounts get {n} days of Pro free.': 'हर ऑर्डर का मिलान खोलने के लिए PakkaBill Pro लें। नए अकाउंट को {n} दिन Pro मुफ़्त मिलता है।',
    'Profit and loss statement, line by line': 'मुनाफ़ा-नुकसान स्टेटमेंट, लाइन-दर-लाइन',
    'RTO, returns and exchanges with every Meesho fee': 'RTO, रिटर्न और एक्सचेंज, Meesho की हर फ़ीस के साथ',
    'Profit by product and by category, with break-even price': 'प्रोडक्ट और कैटेगरी के हिसाब से मुनाफ़ा, ब्रेक-ईवन कीमत के साथ',
    'GST, TCS and TDS worked out': 'GST, TCS और TDS का पूरा हिसाब',
    'Month by month': 'महीने-दर-महीने',
    'Download as PDF and Excel': 'PDF और Excel में डाउनलोड',
    'Every order with its Meesho payment, side by side': 'हर ऑर्डर और उसका Meesho पेमेंट, साथ-साथ',
    'Payments overdue, recoveries and rows that do not add up': 'देर से आने वाले पेमेंट, रिकवरी और न जुड़ने वाली लाइनें',
    'Mark each return or RTO as resellable or not': 'हर रिटर्न या RTO को दोबारा बिकने लायक है या नहीं, मार्क करें',
    'Search by order ID or SKU': 'ऑर्डर ID या SKU से खोजें',
    'Log in or sign up free': 'लॉग इन करें या मुफ़्त साइन अप करें',
    'Get PakkaBill Pro': 'PakkaBill Pro लें',
    'Log in with an account that has Pro to see it here.': 'यहाँ देखने के लिए Pro वाले अकाउंट से लॉग इन करें।',

    /* P&L statement */
    'Profit and loss statement': 'मुनाफ़ा-नुकसान स्टेटमेंट',
    'Particulars': 'विवरण',
    'Amount (₹)': 'रकम (₹)',
    'Revenue': 'आमदनी',
    'Gross sales (incl. GST)': 'कुल बिक्री (GST सहित)',
    'Less: customer returns': 'घटाएँ: ग्राहक रिटर्न',
    'Net sales (incl. GST)': 'नेट बिक्री (GST सहित)',
    'Less: output GST on net sales': 'घटाएँ: नेट बिक्री पर आउटपुट GST',
    'Net revenue': 'नेट आमदनी',
    'Cost of goods sold': 'बिके माल की लागत',
    'Cost of goods shipped ({n} pieces)': 'भेजे गए माल की लागत ({n} पीस)',
    'Returned goods back in stock ({n} pieces)': 'स्टॉक में लौटा माल ({n} पीस)',
    'Total cost of goods sold': 'बिके माल की कुल लागत',
    'Less: cost of goods sold': 'घटाएँ: बिके माल की लागत',
    'Gross profit': 'कुल मुनाफ़ा (ग्रॉस)',
    'Meesho charges': 'Meesho के चार्ज',
    'Meesho charges (excl. GST)': 'Meesho के चार्ज (GST के बिना)',
    'Commission': 'कमीशन',
    'Shipping charges': 'शिपिंग चार्ज',
    'Forward shipping': 'भेजने की शिपिंग',
    'Return / RTO shipping': 'रिटर्न / RTO शिपिंग',
    'Other support services': 'दूसरी सपोर्ट सेवाएँ',
    'Total Meesho charges': 'Meesho के कुल चार्ज',
    'Packaging ({n} parcels)': 'पैकिंग ({n} पार्सल)',
    'Marketing': 'मार्केटिंग',
    'Meesho Ads (excl. GST)': 'Meesho विज्ञापन (GST के बिना)',
    'Total marketing': 'कुल मार्केटिंग',
    'Claims, compensation & recoveries': 'क्लेम, मुआवज़ा और रिकवरी',
    'Referral payments': 'रेफ़रल पेमेंट',
    'Account-level compensation & recovery': 'अकाउंट स्तर का मुआवज़ा और रिकवरी',
    'Recoveries by Meesho': 'Meesho की रिकवरी',
    'Total claims & credits': 'कुल क्लेम और क्रेडिट',
    'Unexplained difference vs Final Settlement': 'फ़ाइनल सेटलमेंट से बिना कारण का फ़र्क',
    'Operating expenses': 'चलाने के खर्च',
    'Other business expenses': 'कारोबार के दूसरे खर्च',
    'Total operating expenses': 'चलाने के कुल खर्च',
    'Less: operating expenses': 'घटाएँ: चलाने के खर्च',
    'Less: GST payable (output GST minus input credit)': 'घटाएँ: देय GST (आउटपुट GST में से इनपुट क्रेडिट घटाकर)',
    'Add back: TCS & TDS deducted (you claim these)': 'वापस जोड़ें: कटा हुआ TCS और TDS (आप इन्हें क्लेम करते हैं)',
    'Brackets mean a cost or a deduction.': 'ब्रैकेट का मतलब खर्च या कटौती है।',
    'Brackets mean a cost or a deduction. Sales and charges are shown without GST; the GST section below has the tax.': 'ब्रैकेट का मतलब खर्च या कटौती है। बिक्री और चार्ज GST के बिना दिखाए गए हैं; टैक्स नीचे GST वाले हिस्से में है।',
    'Sample blouse store, {d} to {d}, counted by payment date': 'Sample blouse store, {d} से {d}, पेमेंट की तारीख से गिना',
    'Sample blouse store, {d} to {d}, counted by order date': 'Sample blouse store, {d} से {d}, ऑर्डर की तारीख से गिना',

    /* returns section */
    'Returns, RTO and exchanges': 'रिटर्न, RTO और एक्सचेंज',
    'Total money lost': 'कुल नुकसान',
    'RTO': 'RTO',
    'Returns': 'रिटर्न',
    'Exchanges': 'एक्सचेंज',
    'Lost': 'खो गए',
    'Came back undelivered': 'डिलीवरी हुए बिना लौटे',
    'Customer sent it back': 'ग्राहक ने लौटाया',
    'Swapped for size or colour': 'साइज़ या रंग के लिए बदला',
    'Lost by the courier': 'कूरियर ने खो दिया',
    '{n} of {n} orders shipped': '{n2} भेजे गए ऑर्डर में से {n1}',
    '{n} of {n} orders delivered': '{n2} डिलीवर ऑर्डर में से {n1}',
    'Money lost': 'नुकसान',
    '{n} per order': '{n} प्रति ऑर्डर',
    'Return shipping fee': 'रिटर्न शिपिंग फ़ीस',
    'Meesho fees kept': 'Meesho ने रखी फ़ीस',
    'Packing': 'पैकिंग',
    'Stock not resellable': 'दोबारा न बिकने वाला स्टॉक',
    'Paid back by Meesho': 'Meesho ने वापस दिया',
    'Still a sale, no extra fee': 'यह बिक्री ही है, कोई अतिरिक्त फ़ीस नहीं',
    'No fees charged': 'कोई फ़ीस नहीं लगी',
    'How this is counted': 'यह कैसे गिना गया',
    'RTO rates are of parcels shipped; return and exchange rates are of orders delivered.': 'RTO दर भेजे गए पार्सल पर है; रिटर्न और एक्सचेंज दर डिलीवर हुए ऑर्डर पर है।',
    'RTO and lost rates are of parcels shipped; return and exchange rates are of orders delivered.': 'RTO और खोए पार्सल की दर भेजे गए पार्सल पर है; रिटर्न और एक्सचेंज दर डिलीवर हुए ऑर्डर पर है।',
    'Money lost is what Meesho cut from your payout for these orders (including GST), plus packing and stock you could not resell, less what Meesho paid back.': 'नुकसान = इन ऑर्डर पर Meesho ने आपके पेमेंट से जो काटा (GST सहित), साथ में पैकिंग और वह स्टॉक जो दोबारा नहीं बिक सका, उसमें से Meesho ने जो लौटाया वह घटाकर।',
    'Exchanges are still sales, so only extra return or exchange fees count as lost.': 'एक्सचेंज बिक्री ही है, इसलिए सिर्फ़ अतिरिक्त रिटर्न या एक्सचेंज फ़ीस नुकसान में गिनी जाती है।',
    '{n} orders are marked returned or RTO but Meesho has not taken the sale back yet, so some fees may still come.': '{n} ऑर्डर रिटर्न या RTO मार्क हैं पर Meesho ने अभी बिक्री वापस नहीं काटी, इसलिए कुछ फ़ीस अभी आ सकती है।',
    '{n} order is marked returned or RTO but Meesho has not taken the sale back yet, so some fees may still come.': '{n} ऑर्डर रिटर्न या RTO मार्क है पर Meesho ने अभी बिक्री वापस नहीं काटी, इसलिए कुछ फ़ीस अभी आ सकती है।',
    '{n} orders have no payment row yet, so their fees are not counted.': '{n} ऑर्डर की अभी कोई पेमेंट लाइन नहीं है, इसलिए उनकी फ़ीस नहीं गिनी गई।',
    '{n} order have no payment row yet, so their fees are not counted.': '{n} ऑर्डर की अभी कोई पेमेंट लाइन नहीं है, इसलिए उसकी फ़ीस नहीं गिनी गई।',
    '{n} orders still in transit are left out.': 'रास्ते में चल रहे {n} ऑर्डर नहीं गिने गए।',
    '{n} order still in transit are left out.': 'रास्ते में चल रहा {n} ऑर्डर नहीं गिना गया।',
    'RTO parcels and returns count as back in stock unless marked Not resellable in Reconcile or Settings. Counted by payment date.': 'RTO पार्सल और रिटर्न वापस स्टॉक में गिने जाते हैं, जब तक मिलान या सेटिंग्स में "दोबारा बिकने लायक नहीं" मार्क न करें। पेमेंट की तारीख से गिना।',
    'RTO parcels and returns count as back in stock unless marked Not resellable in Reconcile or Settings. Counted by order date.': 'RTO पार्सल और रिटर्न वापस स्टॉक में गिने जाते हैं, जब तक मिलान या सेटिंग्स में "दोबारा बिकने लायक नहीं" मार्क न करें। ऑर्डर की तारीख से गिना।',
    'Each Meesho fee on returns and RTO': 'रिटर्न और RTO पर Meesho की हर फ़ीस',
    'Column in Meesho file': 'Meesho फ़ाइल का कॉलम',
    'Minus is money Meesho took; plus is money it gave back on these orders.': 'माइनस = Meesho ने लिया; प्लस = इन ऑर्डर पर Meesho ने लौटाया।',
    'RTO, returns and exchanges by SKU': 'SKU के हिसाब से RTO, रिटर्न और एक्सचेंज',
    'Shipped': 'भेजे गए',
    'Red is {n} or more. A high RTO rate often means buyers change their mind before delivery (try fewer COD orders to far pincodes); a high return rate usually points to size, colour or quality not matching the photos.': 'लाल = {n} या ज़्यादा। ज़्यादा RTO का मतलब अक्सर ग्राहक डिलीवरी से पहले मन बदल लेते हैं (दूर के पिनकोड पर COD ऑर्डर कम रखें); ज़्यादा रिटर्न का मतलब अक्सर साइज़, रंग या क्वालिटी फ़ोटो से मेल नहीं खाती।',
    'Red is {n} or more. Showing the {n} SKUs that lose the most; the Excel download has all of them. A high RTO rate often means buyers change their mind before delivery (try fewer COD orders to far pincodes); a high return rate usually points to size, colour or quality not matching the photos.': 'लाल = {n} या ज़्यादा। सबसे ज़्यादा नुकसान वाले {n} SKU दिखाए हैं; Excel डाउनलोड में सभी हैं। ज़्यादा RTO का मतलब अक्सर ग्राहक डिलीवरी से पहले मन बदल लेते हैं (दूर के पिनकोड पर COD ऑर्डर कम रखें); ज़्यादा रिटर्न का मतलब अक्सर साइज़, रंग या क्वालिटी फ़ोटो से मेल नहीं खाती।',

    /* category */
    'Profit by category': 'कैटेगरी के हिसाब से मुनाफ़ा',
    'Category': 'कैटेगरी',
    'Profit': 'मुनाफ़ा',
    'Margin': 'मार्जिन',
    'Orders': 'ऑर्डर',
    'RTO + returns': 'RTO + रिटर्न',
    'Lost on them': 'इन पर नुकसान',
    'All categories': 'सभी कैटेगरी',
    '{n} SKUs': '{n} SKU',
    '{n} SKU': '{n} SKU',
    'Categories come from a Category column in your uploaded files when there is one (for example Meesho’s catalogue download), otherwise from Meesho’s product names. Change any SKU’s category in the Costs tab. Profit is before ads and other expenses, like Profit by SKU.': 'कैटेगरी आपकी अपलोड फ़ाइल के Category कॉलम से ली जाती है (जैसे Meesho का कैटलॉग डाउनलोड), नहीं तो Meesho के प्रोडक्ट नाम से। किसी भी SKU की कैटेगरी लागत टैब में बदलें। यह मुनाफ़ा विज्ञापन और दूसरे खर्च से पहले का है, SKU वाले मुनाफ़े की तरह।',

    /* bridge */
    'How profit ties to money received': 'मुनाफ़ा और मिले पैसे का मिलान',
    'Money received from Meesho': 'Meesho से मिला पैसा',
    'Order settlements (sum of Final Settlement Amount)': 'ऑर्डर सेटलमेंट (Final Settlement Amount का जोड़)',
    'Ads cost deducted': 'कटा हुआ विज्ञापन खर्च',
    'Referral and compensation entries': 'रेफ़रल और मुआवज़े की एंट्री',
    'Net received': 'कुल मिला',
    'TCS and TDS deducted by Meesho': 'Meesho ने काटा TCS और TDS',
    'Money received is the sum of Final Settlement Amount plus ads, referral and compensation entries. It should match the Meesho credits in your bank for the same payment dates.': 'मिला पैसा = Final Settlement Amount का जोड़, साथ में विज्ञापन, रेफ़रल और मुआवज़े की एंट्री। यह उन्हीं पेमेंट तारीखों पर आपके बैंक में Meesho से आए पैसे से मिलना चाहिए।',

    /* GST */
    'GST, TCS and TDS': 'GST, TCS और TDS',
    'Output GST on net sales': 'नेट बिक्री पर आउटपुट GST',
    'Less: input credit on Meesho charges': 'घटाएँ: Meesho चार्ज पर इनपुट क्रेडिट',
    'Less: input credit on ads': 'घटाएँ: विज्ञापन पर इनपुट क्रेडिट',
    'Net GST payable': 'कुल देय GST',
    'Less: TCS already collected by Meesho': 'घटाएँ: Meesho का पहले से काटा TCS',
    'GST left to pay in cash': 'नकद में भरने बाकी GST',
    'Less: input credit on goods bought with a GST bill': 'घटाएँ: GST बिल पर खरीदे माल का इनपुट क्रेडिट',
    'Input credit more than GST on sales': 'इनपुट क्रेडिट बिक्री के GST से ज़्यादा',
    'GST credit carried forward (nothing to pay in cash)': 'अगली बार के लिए बचा GST क्रेडिट (नकद में कुछ नहीं भरना)',
    'Cost of goods sold (without the GST you claim back)': 'बेचे गए माल की लागत (वापस मिलने वाले GST के बिना)',
    'Less: GST paid to suppliers on these goods (claimed back above)': 'घटाएँ: इस माल पर सप्लायर को दिया GST (ऊपर वापस लिया)',
    'Add: input credit left over (carried to the next GST return)': 'जोड़ें: बचा इनपुट क्रेडिट (अगले GST रिटर्न में जाएगा)',
    'Goods you buy come with': 'आप जो माल खरीदते हैं, उसके साथ',
    'Tax credits not counted as profit': 'टैक्स क्रेडिट जो मुनाफ़े में नहीं गिने',
    'TCS more than the GST left to pay (stays in the GST cash ledger for future GST)': 'बाकी GST से ज़्यादा TCS (आगे के GST के लिए GST कैश लेजर में रहता है)',
    'TCS deducted by Meesho (no GST registration to use it)': 'Meesho का काटा TCS (GST रजिस्ट्रेशन नहीं, इसलिए काम नहीं आएगा)',
    'TCS not counted as profit (only pays future GST)': 'मुनाफ़े में न गिना TCS (सिर्फ़ आगे का GST भरता है)',
    'Add back: TDS (claimed in your ITR) and the TCS used to pay GST': 'जोड़ें: TDS (ITR में वापस मिलेगा) और GST भरने में लगा TCS',
    'TDS is added back to profit: you get it back when you file your income tax return (it shows in Form 26AS).': 'TDS मुनाफ़े में वापस जोड़ा गया: इनकम टैक्स रिटर्न भरने पर यह वापस मिलता है (Form 26AS में दिखता है)।',
    'Without GST registration the TCS cannot be used, so it is not counted as profit.': 'GST रजिस्ट्रेशन के बिना TCS काम नहीं आता, इसलिए मुनाफ़े में नहीं गिना।',
    'TCS sits in your GST cash ledger and can only pay GST.': 'TCS आपके GST कैश लेजर में रहता है और सिर्फ़ GST भरने में काम आता है।',
    '{n} of it is more than the GST left to pay, so it is not counted as profit; it stays there for future GST.': 'इसमें से {n} बाकी GST से ज़्यादा है, इसलिए मुनाफ़े में नहीं गिना; यह आगे के GST के लिए वहीं रहता है।',
    'TCS sits in your GST cash ledger and can only pay GST, so it counts as profit only up to the GST you have to pay.': 'TCS आपके GST कैश लेजर में रहता है और सिर्फ़ GST भरता है, इसलिए यह उतना ही मुनाफ़े में गिना जाता है जितना GST आपको भरना है।',
    'Here all of it is used.': 'यहाँ पूरा काम आ गया।',
    'GST input credit not usable yet': 'GST इनपुट क्रेडिट जो अभी काम नहीं आएगा',
    'Input credit more than GST on sales (kept in the GST portal to pay future GST, not cash)': 'बिक्री के GST से ज़्यादा इनपुट क्रेडिट (GST पोर्टल में आगे का GST भरने के लिए रहता है, नकद नहीं मिलता)',
    'Total credit not counted as profit': 'कुल क्रेडिट जो मुनाफ़े में नहीं गिना',
    'Input credit not counted as profit (only pays future GST)': 'मुनाफ़े में न गिना इनपुट क्रेडिट (सिर्फ़ आगे का GST भरता है)',
    'GST payable: none (input credit covers it; the extra credit is not counted as profit)': 'देय GST: कुछ नहीं (इनपुट क्रेडिट से भर गया; बचा क्रेडिट मुनाफ़े में नहीं गिना)',
    'GST bill': 'GST बिल',
    'No GST bill': 'GST बिल नहीं',
    '{n} GST bill': '{n} GST बिल',
    'Same as default (No GST bill)': 'डिफ़ॉल्ट जैसा (GST बिल नहीं)',
    'Same as default ({n} GST bill)': 'डिफ़ॉल्ट जैसा ({n} GST बिल)',
    '{n} per piece after {n} GST credit': '{n2} GST क्रेडिट के बाद {n1} प्रति पीस',
    'Goods counted as bought with a {n} GST bill': 'माल {n} GST बिल पर खरीदा माना गया',
    'Goods counted as bought without a GST bill': 'माल बिना GST बिल के खरीदा माना गया',
    'Enter the cost you paid, including GST. With a GST bill, the GST in it is your input credit: it lowers the GST you pay in cash, so the product costs you the price without GST. Credit beyond the GST on your sales is never paid out; it only pays future GST, so it is not counted as profit. Change it for any SKU below.': 'जो कीमत आपने दी, GST समेत, वही लिखें। GST बिल हो तो उसमें का GST आपका इनपुट क्रेडिट है: इससे नकद में भरने वाला GST कम होता है, इसलिए माल की लागत GST के बिना वाली कीमत होती है। बिक्री के GST से ज़्यादा क्रेडिट कभी नकद नहीं मिलता, सिर्फ़ आगे का GST भरता है, इसलिए मुनाफ़े में नहीं गिना जाता। नीचे किसी भी SKU के लिए बदल सकते हैं।',
    'You are not registered under GST (see Settings), so GST on purchases cannot be claimed back and the full price you paid is the cost.': 'आप GST में रजिस्टर्ड नहीं हैं (सेटिंग्स देखें), इसलिए खरीद पर दिया GST वापस नहीं मिलता और पूरी दी गई कीमत ही लागत है।',
    'Meesho deducted {n} TCS (under GST) and {n} TDS (income tax, section {n}-O) from these payouts. Both are added back to profit because you can claim them: TCS in your GST return and TDS in your income tax return, where it shows in Form {n}AS.': 'Meesho ने इन पेमेंट से {n} TCS (GST के तहत) और {n} TDS (इनकम टैक्स, धारा {n}-O) काटा। दोनों मुनाफ़े में वापस जोड़े गए हैं क्योंकि आप इन्हें क्लेम कर सकते हैं: TCS अपने GST रिटर्न में और TDS इनकम टैक्स रिटर्न में, जो फ़ॉर्म {n}AS में दिखता है।',
    'Input credit is worked out at {n} on the columns Meesho marks as including GST. Check it against Meesho’s monthly tax invoice before you file.': 'इनपुट क्रेडिट उन कॉलम पर {n} से निकाला है जिन्हें Meesho GST सहित बताता है। रिटर्न भरने से पहले Meesho के मासिक टैक्स इनवॉइस से मिला लें।',
    'GST is not split out because GST registration is off in Settings. Meesho charges and ads are counted including GST.': 'GST अलग नहीं दिखाया क्योंकि सेटिंग्स में GST रजिस्ट्रेशन बंद है। Meesho चार्ज और विज्ञापन GST सहित गिने गए हैं।',

    /* SKU */
    'Profit by SKU': 'SKU के हिसाब से मुनाफ़ा',
    'Pieces': 'पीस',
    'Returns and RTO': 'रिटर्न और RTO',
    'Per order': 'प्रति ऑर्डर',
    'Delivered': 'डिलीवर',
    'Per delivered order': 'प्रति डिलीवर ऑर्डर',
    'Delivered (no return or RTO)': 'डिलीवर (रिटर्न या RTO नहीं)',
    'Profit per delivered order': 'प्रति डिलीवर ऑर्डर मुनाफ़ा',
    'Price now': 'अभी की कीमत',
    'Break-even price': 'ब्रेक-ईवन कीमत',
    'Not tied to a SKU (ads, referral, account credits, expenses)': 'किसी SKU से नहीं जुड़ा (विज्ञापन, रेफ़रल, अकाउंट क्रेडिट, खर्च)',
    'pack of {n}': '{n} का पैक',
    'SKU profit is after cost of goods, Meesho charges and packaging, before ads and other expenses. Per delivered order is that profit divided by the orders delivered and kept: returned and RTO orders are left out of the count, but the money lost on them stays in the profit. Price now is what buyers paid per order on average. Break-even price is the customer price where the SKU’s profit per order would be zero, with the same returns, GST and charges; red means it is above today’s price, so the SKU loses money.': 'SKU का मुनाफ़ा माल की लागत, Meesho चार्ज और पैकिंग के बाद का है, विज्ञापन और दूसरे खर्च से पहले का। प्रति डिलीवर ऑर्डर = यह मुनाफ़ा ÷ वे ऑर्डर जो डिलीवर होकर ग्राहक के पास रहे: रिटर्न और RTO ऑर्डर गिनती में नहीं, पर उन पर हुआ नुकसान मुनाफ़े में घटा हुआ है। अभी की कीमत = ग्राहक ने औसतन प्रति ऑर्डर कितना दिया। ब्रेक-ईवन कीमत = वह कीमत जिस पर इसी रिटर्न, GST और चार्ज के साथ प्रति ऑर्डर मुनाफ़ा शून्य होगा; लाल का मतलब यह आज की कीमत से ऊपर है, यानी इस SKU पर नुकसान है।',
    'Month': 'महीना',
    'Received': 'मिला',
    'Counted by payment date. Monthly expenses are included in each month.': 'पेमेंट की तारीख से गिना। मासिक खर्च हर महीने में जोड़े गए हैं।',
    'Counted by order date. Monthly expenses are included in each month.': 'ऑर्डर की तारीख से गिना। मासिक खर्च हर महीने में जोड़े गए हैं।',

    /* reconcile */
    'All orders': 'सभी ऑर्डर',
    'Needs attention': 'ध्यान दें',
    'Paid': 'पेमेंट मिला',
    'Awaiting payment': 'पेमेंट का इंतज़ार',
    'Payment overdue': 'पेमेंट में देरी',
    'In transit': 'रास्ते में',
    'Customer returns': 'ग्राहक रिटर्न',
    'RTO and lost': 'RTO और खोए',
    'Cancelled': 'रद्द',
    'Adjustment only': 'सिर्फ़ एडजस्टमेंट',
    'Before these files': 'इन फ़ाइलों से पहले के',
    'Other': 'दूसरे',
    'Filter orders': 'ऑर्डर छाँटें',
    'Search orders': 'ऑर्डर खोजें',
    'Search sub order number or SKU': 'सब ऑर्डर नंबर या SKU खोजें',
    'Every sub order in your files. The amount is what Meesho paid for it, all payment rows added up.': 'आपकी फ़ाइलों का हर सब ऑर्डर। रकम = Meesho ने इसके लिए जो दिया, सारी पेमेंट लाइनें जोड़कर।',
    'Recoveries, rows that do not add up, negative payouts, paid-but-cancelled orders and overdue payments.': 'रिकवरी, न जुड़ने वाली लाइनें, माइनस पेमेंट, पेमेंट मिलने के बाद रद्द ऑर्डर और देर वाले पेमेंट।',
    'Orders with a sale settlement from Meesho.': 'जिन ऑर्डर का Meesho से बिक्री सेटलमेंट आ गया।',
    'Delivered orders with no payment yet, still inside the normal payment window.': 'डिलीवर हुए ऑर्डर जिनका पेमेंट अभी नहीं आया, पर अभी सामान्य समय के अंदर हैं।',
    'Delivered orders placed more than {n} days before your latest payment date, still without a payment. Raise a ticket with Meesho if it is not in the next payout.': 'डिलीवर हुए ऑर्डर जो आपकी आख़िरी पेमेंट तारीख से {n} दिन से ज़्यादा पहले के हैं और अभी तक पेमेंट नहीं आया। अगले पेमेंट में न आए तो Meesho पर टिकट डालें।',
    'Shipped orders not delivered yet.': 'भेजे गए ऑर्डर जो अभी डिलीवर नहीं हुए।',
    'Customer returns. They count as back in stock; mark any that came back damaged, used or wrong as Not resellable.': 'ग्राहक रिटर्न। ये वापस स्टॉक में गिने जाते हैं; जो खराब, इस्तेमाल किया हुआ या गलत लौटा, उसे "दोबारा बिकने लायक नहीं" मार्क करें।',
    'Parcels that came back undelivered, and lost parcels. Mark whether each item went back into stock.': 'बिना डिलीवरी लौटे और खोए पार्सल। हर सामान के लिए मार्क करें कि स्टॉक में वापस गया या नहीं।',
    'Cancelled orders.': 'रद्द ऑर्डर।',
    'Payment rows without a sale in these files, such as fee adjustments for orders paid earlier.': 'बिना बिक्री वाली पेमेंट लाइनें, जैसे पहले पेमेंट हो चुके ऑर्डर की फ़ीस का एडजस्टमेंट।',
    'Orders placed well before your first payment date. Upload older payment files to settle them.': 'आपकी पहली पेमेंट तारीख से काफ़ी पहले के ऑर्डर। इनके लिए पुरानी पेमेंट फ़ाइलें अपलोड करें।',
    'Orders with a status the tool could not place.': 'ऐसे स्टेटस वाले ऑर्डर जिन्हें टूल समझ नहीं पाया।',
    'Recovery charged': 'रिकवरी कटी',
    'Does not add up': 'जोड़ नहीं मिलता',
    'Paid but cancelled': 'पेमेंट मिला पर रद्द',
    'Negative payout': 'माइनस पेमेंट',
    'Claim received': 'क्लेम मिला',
    'Sale not reversed yet': 'बिक्री अभी वापस नहीं कटी',
    'Back in stock': 'वापस स्टॉक में',
    'Not resellable': 'दोबारा बिकने लायक नहीं',
    'default, not checked': 'डिफ़ॉल्ट, जाँचा नहीं',
    'Delivered': 'डिलीवर',
    'Delivered, ordered {d}': 'डिलीवर, ऑर्डर {d}',
    'Delivered, ordered {d}, last paid {d}': 'डिलीवर, ऑर्डर {d}, आख़िरी पेमेंट {d}',
    'Cancelled, ordered {d}': 'रद्द, ऑर्डर {d}',
    'Customer return, ordered {d}': 'ग्राहक रिटर्न, ऑर्डर {d}',
    'Customer return, ordered {d}, last paid {d}': 'ग्राहक रिटर्न, ऑर्डर {d}, आख़िरी पेमेंट {d}',
    'Exchanged, ordered {d}': 'एक्सचेंज, ऑर्डर {d}',
    'Exchanged, ordered {d}, last paid {d}': 'एक्सचेंज, ऑर्डर {d}, आख़िरी पेमेंट {d}',
    'In transit, ordered {d}': 'रास्ते में, ऑर्डर {d}',
    'RTO, ordered {d}': 'RTO, ऑर्डर {d}',
    'RTO, ordered {d}, last paid {d}': 'RTO, ऑर्डर {d}, आख़िरी पेमेंट {d}',
    'paid {d}': 'पेमेंट {d}',
    'Show {n} more of {n}': '{n2} में से {n1} और दिखाएँ',
    'Item condition for {n}_{n}': '{n}_{n} का सामान किस हालत में है',
    'Return': 'रिटर्न',

    /* upload tab */
    'Add your Meesho reports': 'अपनी Meesho रिपोर्ट जोड़ें',
    'Payment report': 'पेमेंट रिपोर्ट',
    'In the Meesho Supplier Panel, open': 'Meesho सप्लायर पैनल में खोलें',
    'Payments': 'पेमेंट',
    'and download the payment report for the dates you want. It is an Excel file with sheets such as Order Payments and Ads Cost. Add every payment file you have; rows that repeat across files are counted once.': 'और जिन तारीखों की चाहिए उनकी पेमेंट रिपोर्ट डाउनलोड करें। यह Excel फ़ाइल होती है जिसमें Order Payments और Ads Cost जैसी शीट होती हैं। जितनी पेमेंट फ़ाइलें हैं सब जोड़ें; दोहराई गई लाइनें एक ही बार गिनी जाती हैं।',
    'Orders report (optional)': 'ऑर्डर रिपोर्ट (ज़रूरी नहीं)',
    'Orders report': 'ऑर्डर रिपोर्ट',
    'Orders': 'ऑर्डर',
    ', download the orders CSV. It adds orders that are not paid yet, so pending and overdue payments show up.': ' से ऑर्डर CSV डाउनलोड करें। इससे वे ऑर्डर भी जुड़ते हैं जिनका पेमेंट अभी नहीं आया, ताकि बाकी और देर वाले पेमेंट दिखें।',
    'Drop Meesho files here': 'Meesho फ़ाइलें यहाँ डालें',
    'or tap to choose. Excel (.xlsx, .xls), CSV or ZIP, many at once. ZIP files are opened for you.': 'या टैप करके चुनें। Excel (.xlsx, .xls), CSV या ZIP, एक साथ कई। ZIP फ़ाइलें अपने आप खुल जाती हैं।',
    'Uploaded files': 'अपलोड की गई फ़ाइलें',
    'What your files cover': 'आपकी फ़ाइलों में क्या है',
    'Files are read on this device and kept here for next time. Costs, expenses, return marks and settings are saved in this browser.': 'फ़ाइलें इसी डिवाइस पर पढ़ी जाती हैं और अगली बार के लिए यहीं रहती हैं। लागत, खर्च, रिटर्न मार्क और सेटिंग्स इसी ब्राउज़र में सेव रहती हैं।',
    'Remove all': 'सब हटाएँ',
    'Remove': 'हटाएँ',
    'Remove uploaded files': 'अपलोड की फ़ाइलें हटाएँ',
    'added {d}': 'जोड़ी {d}',
    'Order Payments: {n} settlement rows, paid {d} to {d}. {n} of {n} rows add up exactly to Final Settlement': 'Order Payments: {n} सेटलमेंट लाइनें, पेमेंट {d} से {d}। {n3} में से {n2} लाइनें Final Settlement से बिल्कुल मिलती हैं',
    'Ads Cost: {n} ads deductions': 'Ads Cost: विज्ञापन की {n} कटौतियाँ',
    'Referral Payments: {n} referral payments': 'Referral Payments: {n} रेफ़रल पेमेंट',
    'Compensation and Recovery: {n} compensation and recovery entries': 'Compensation and Recovery: मुआवज़े और रिकवरी की {n} एंट्री',
    'Orders: {n} orders, ordered {d} to {d}': 'Orders: {n} ऑर्डर, {d} से {d} तक के',
    'Disclaimer: not used': 'Disclaimer: इस्तेमाल नहीं हुई',
    'Payment dates': 'पेमेंट की तारीखें',
    'Settlement rows': 'सेटलमेंट लाइनें',
    'Rows that add up to Final Settlement': 'Final Settlement से मिलने वाली लाइनें',
    'Ads deductions': 'विज्ञापन कटौतियाँ',
    'Payouts by date ({n})': 'तारीख के हिसाब से पेमेंट ({n})',
    'Match each net amount with the Meesho credit in your bank statement. The transaction ID helps you find it.': 'हर नेट रकम को बैंक स्टेटमेंट में Meesho से आए पैसे से मिलाएँ। ट्रांज़ैक्शन ID से ढूँढना आसान है।',
    '{n} payment rows': '{n} पेमेंट लाइनें',
    'Settlements': 'सेटलमेंट',
    'Ads': 'विज्ञापन',
    'Sample files': 'सैंपल फ़ाइलें',
    'Close sample': 'सैंपल बंद करें',
    'You are looking at sample data for a blouse and track pant store. Nothing here is saved.': 'आप एक ब्लाउज़ और ट्रैक पैंट की दुकान का सैंपल डेटा देख रहे हैं। यहाँ कुछ भी सेव नहीं होता।',
    'Upload the payment report from the Meesho Supplier Panel. PakkaBill takes out every fee, return, RTO, GST and product cost, and shows what you really earned. Or look around with sample data first.': 'Meesho सप्लायर पैनल से पेमेंट रिपोर्ट अपलोड करें। PakkaBill हर फ़ीस, रिटर्न, RTO, GST और प्रोडक्ट की लागत घटाकर दिखाता है कि आपने असल में कितना कमाया। या पहले सैंपल डेटा से देख लें।',
    'See profit and loss': 'मुनाफ़ा-नुकसान देखें',
    'Enter product costs': 'प्रोडक्ट की लागत भरें',
    'Enter what one unit of each SKU costs you.': 'हर SKU की एक यूनिट आपको कितने में पड़ती है, भरें।',
    'Working': 'काम चल रहा है',
    'Reading your files': 'आपकी फ़ाइलें पढ़ी जा रही हैं',
    'Building the Excel file': 'Excel फ़ाइल बन रही है',
    'Building the PDF': 'PDF बन रही है',

    /* costs tab */
    'Product costs': 'प्रोडक्ट की लागत',
    'Enter what one piece costs you to buy or make, in rupees. For a combo SKU the tool multiplies it by the pieces in the pack.': 'एक पीस खरीदने या बनाने में कितने रुपये लगते हैं, भरें। कॉम्बो SKU में टूल इसे पैक के पीस से गुणा कर देता है।',
    '{n} of {n} have a cost': '{n2} में से {n1} की लागत भरी है',
    'Fill costs automatically': 'लागत अपने आप भरें',
    'One cost per piece for a whole group: a category, or every SKU with the same word in it.': 'पूरे ग्रुप के लिए एक ही लागत: एक कैटेगरी, या नाम में एक जैसा शब्द वाले सभी SKU।',
    'Same cost': 'एक जैसी लागत',
    '% of price': 'कीमत का %',
    'Copy similar': 'मिलते-जुलते से कॉपी',
    'Paste list': 'लिस्ट पेस्ट करें',
    'Which SKUs': 'कौन से SKU',
    'All SKUs ({n})': 'सभी SKU ({n})',
    'Text in the SKU or product name': 'SKU या प्रोडक्ट नाम में शब्द',
    'Part of SKU or product name': 'SKU या प्रोडक्ट नाम का हिस्सा',
    'SKUs with this text…': 'इस शब्द वाले SKU…',
    'Only missing': 'सिर्फ़ बाकी वाले',
    'Only SKUs that have no cost yet': 'सिर्फ़ वे SKU जिनकी लागत अभी नहीं भरी',
    'Per piece (₹)': 'प्रति पीस (₹)',
    'Cost per piece in rupees': 'प्रति पीस लागत रुपये में',
    '₹ per piece': '₹ प्रति पीस',
    'Fill': 'भरें',
    'Undo': 'वापस लें',
    'How to fill': 'कैसे भरें',
    'Your SKUs': 'आपके SKU',
    'Search SKU': 'SKU खोजें',
    'Cost': 'लागत',
    'order value': 'ऑर्डर वैल्यू',
    '{n} for {n} orders': '{n2} ऑर्डर के लिए {n1}',
    '{n} orders, {n}': '{n} ऑर्डर, {n}',
    '{n} orders, {d} to {d}': '{n} ऑर्डर, {d} से {d}',
    '{n} order, {d} to {d}': '{n} ऑर्डर, {d} से {d}',
    '{n} sold': '{n} बिके',
    'buyer pays {n}': 'ग्राहक देता है {n}',
    '{n} cost per order': 'प्रति ऑर्डर लागत {n}',
    '{n} of price': 'कीमत का {n}',
    'Other expenses': 'दूसरे खर्च',
    '{n} orders, {n} in order value': '{n} ऑर्डर, {n} की ऑर्डर वैल्यू',
    'Download cost sheet': 'लागत शीट डाउनलोड करें',
    'Upload cost sheet': 'लागत शीट अपलोड करें',
    'The cost sheet lists every SKU with its category, the buyer price, pieces and cost per piece. Fill it in Excel and upload it back; a changed category is saved too.': 'लागत शीट में हर SKU उसकी कैटेगरी, ग्राहक कीमत, पीस और प्रति पीस लागत के साथ होता है। Excel में भरकर वापस अपलोड करें; बदली गई कैटेगरी भी सेव हो जाती है।',
    'Upload a payment report to list your SKUs here.': 'अपने SKU यहाँ देखने के लिए पेमेंट रिपोर्ट अपलोड करें।',
    'Pieces in a combo': 'कॉम्बो में पीस',
    'Automatic': 'अपने आप',
    'From the product name': 'प्रोडक्ट के नाम से',
    'From the SKU letters (BPYG05 = {n})': 'SKU के अक्षरों से (BPYG05 = {n})',
    'Automatic: Read from the product name, like "Combo of {n}" or "Pack of {n}"; anything else counts as {n} piece. For any SKU that is different, type the right count under Pieces.': 'अपने आप: प्रोडक्ट के नाम से पढ़ा जाता है, जैसे "Combo of {n}" या "Pack of {n}"; बाकी सब {n} पीस गिना जाता है। जो SKU अलग हो, उसके लिए "पीस" में सही गिनती लिखें।',
    '(auto)': '(अपने आप)',
    '(done)': '(पूरा)',

    /* expenses tab */
    'Your expenses': 'आपके खर्च',
    'Costs outside Meesho’s report. A monthly amount is spread by day, so half a month counts half.': 'Meesho रिपोर्ट के बाहर के खर्च। मासिक रकम दिनों में बाँटी जाती है, यानी आधा महीना = आधी रकम।',
    'What for': 'किस लिए',
    'Rent, packing help, internet': 'किराया, पैकिंग में मदद, इंटरनेट',
    'Rent, packing help, internet, photoshoots.': 'किराया, पैकिंग में मदद, इंटरनेट, फ़ोटोशूट।',
    'Amount': 'रकम',
    'Enter the amount in rupees': 'रकम रुपये में भरें',
    'How often': 'कितनी बार',
    'Every month': 'हर महीने',
    'One time, in one month': 'एक बार, एक महीने में',
    'Add expense': 'खर्च जोड़ें',
    'No expenses added yet.': 'अभी कोई खर्च नहीं जोड़ा।',
    'Delete': 'हटाएँ',
    'Rent': 'किराया',
    'Internet': 'इंटरनेट',
    'Product photoshoot': 'प्रोडक्ट फ़ोटोशूट',
    'Rent (monthly)': 'किराया (मासिक)',
    'Internet (monthly)': 'इंटरनेट (मासिक)',
    'Every month, {n} in {d} to {d}': 'हर महीने, {d} से {d} में {n}',
    'One time, {d}, {n} in {d} to {d}': 'एक बार, {d1}, {d2} से {d3} में {n}',
    'Shown on the P&L': 'P&L पर दिखता है',
    'Open Expenses': 'खर्च खोलें',
    'Open Costs': 'लागत खोलें',

    /* settings tab */
    'Business': 'कारोबार',
    'Business name': 'कारोबार का नाम',
    'Shown on the P&L and on the PDF.': 'P&L और PDF पर दिखता है।',
    'I am registered under GST': 'मैं GST में रजिस्टर्ड हूँ',
    'Turn this off if you sell with a Meesho Enrolment ID instead of a GSTIN. Then GST is not split out and charges count including GST.': 'अगर आप GSTIN की जगह Meesho Enrolment ID से बेचते हैं तो इसे बंद करें। तब GST अलग नहीं दिखेगा और चार्ज GST सहित गिने जाएँगे।',
    'GST rate when the file has none (%)': 'फ़ाइल में GST दर न हो तो यह दर (%)',
    'TCS and TDS': 'TCS और TDS',
    'I claim them back': 'मैं इन्हें वापस क्लेम करता/करती हूँ',
    'Count them as an expense': 'इन्हें खर्च में गिनें',
    'Packaging per parcel (₹)': 'प्रति पार्सल पैकिंग (₹)',
    'Packaging (₹)': 'पैकिंग (₹)',
    'Poly bag, label and tape for one parcel. Counted once per shipped parcel, RTO parcels included.': 'एक पार्सल का पॉली बैग, लेबल और टेप। हर भेजे गए पार्सल पर एक बार गिना जाता है, RTO पार्सल भी।',
    'Returns and payments': 'रिटर्न और पेमेंट',
    'Customer returns usually are': 'ग्राहक रिटर्न आमतौर पर',
    'RTO parcels usually are': 'RTO पार्सल आमतौर पर',
    'Mark each return or RTO in Reconcile to override these.': 'इसे बदलने के लिए मिलान में हर रिटर्न या RTO को अलग से मार्क करें।',
    'Payment overdue after (days from order)': 'पेमेंट कितने दिन बाद देर माना जाए (ऑर्डर से)',
    'Appearance': 'दिखावट',
    'Theme': 'थीम',
    'Match device': 'डिवाइस जैसा',
    'Light': 'हल्का',
    'Dark': 'गहरा',
    'Backup': 'बैकअप',
    'Download your costs, expenses, return marks and settings as a file, or restore them on another device.': 'अपनी लागत, खर्च, रिटर्न मार्क और सेटिंग्स फ़ाइल में डाउनलोड करें, या किसी दूसरे डिवाइस पर वापस लाएँ।',
    'Download backup': 'बैकअप डाउनलोड करें',
    'Restore backup': 'बैकअप वापस लाएँ',
    'Remove data': 'डेटा हटाएँ',
    'Erase everything': 'सब कुछ मिटाएँ',

    /* messages */
    'Showing sample data. Nothing is saved.': 'सैंपल डेटा दिख रहा है। कुछ भी सेव नहीं होता।',
    'File added': 'फ़ाइल जुड़ गई',
    '{n} files added': '{n} फ़ाइलें जुड़ गईं',
    'File removed': 'फ़ाइल हट गई',
    'Uploaded files removed': 'अपलोड की फ़ाइलें हट गईं',
    'Everything erased': 'सब मिट गया',
    'Expense added': 'खर्च जुड़ गया',
    'Backup restored': 'बैकअप वापस आ गया',
    'Saved': 'सेव हो गया',
    'Packaging cost saved': 'पैकिंग लागत सेव हो गई',
    'Download cancelled': 'डाउनलोड रद्द',
    'Cost cannot be negative': 'लागत माइनस नहीं हो सकती',
    'Enter a valid number': 'सही नंबर भरें',
    'Enter a number, like {n} or {n}': 'नंबर भरें, जैसे {n} या {n}',
    'Enter a percentage between {n} and {n}': '{n} से {n} के बीच प्रतिशत भरें',
    'Enter the cost per piece in rupees': 'प्रति पीस लागत रुपये में भरें',
    'Enter the packaging cost in rupees': 'पैकिंग लागत रुपये में भरें',
    'Write what the expense is for': 'लिखें कि खर्च किस लिए है',
    'Pieces must be a whole number from {n} to {n}': 'पीस {n} से {n} के बीच पूरा नंबर होना चाहिए',
    'That is not a Hisaab backup file.': 'यह हिसाब की बैकअप फ़ाइल नहीं है।',
    'Could not read that cost sheet.': 'यह लागत शीट पढ़ी नहीं जा सकी।',
    'No rows found. The sheet needs an SKU column and a Cost column.': 'कोई लाइन नहीं मिली। शीट में SKU और Cost कॉलम होने चाहिए।',
    'Paste rows like: SKU, cost per piece (copied from Excel)': 'ऐसे लाइनें पेस्ट करें: SKU, प्रति पीस लागत (Excel से कॉपी करके)',
    'Could not keep the uploaded data on this device. It will be gone after a reload.': 'अपलोड किया डेटा इस डिवाइस पर नहीं रखा जा सका। पेज दोबारा खोलने पर यह चला जाएगा।',
    'A download is already waiting for your answer. Try again in a moment.': 'एक डाउनलोड पहले से आपके जवाब का इंतज़ार कर रहा है। थोड़ी देर में फिर कोशिश करें।',
    'This file is too large to save here.': 'यह फ़ाइल यहाँ सेव करने के लिए बहुत बड़ी है।',
    'This file type cannot be saved here.': 'इस तरह की फ़ाइल यहाँ सेव नहीं हो सकती।',
    'Remove all uploaded files from this device? Costs, expenses and settings stay.': 'इस डिवाइस से सभी अपलोड फ़ाइलें हटाएँ? लागत, खर्च और सेटिंग्स बनी रहेंगी।',
    'Erase uploaded files, costs, expenses, return marks and settings? This cannot be undone.': 'अपलोड फ़ाइलें, लागत, खर्च, रिटर्न मार्क और सेटिंग्स मिटाएँ? यह वापस नहीं होगा।',
    'Could not build the file.': 'फ़ाइल नहीं बन सकी।',
    'Could not read the files.': 'फ़ाइलें पढ़ी नहीं जा सकीं।'
  };

  var MONTHS = { Jan: 'जनवरी', Feb: 'फ़रवरी', Mar: 'मार्च', Apr: 'अप्रैल', May: 'मई', Jun: 'जून', Jul: 'जुलाई', Aug: 'अगस्त', Sep: 'सितंबर', Sept: 'सितंबर', Oct: 'अक्टूबर', Nov: 'नवंबर', Dec: 'दिसंबर' };
  var DATE = /\b(\d{1,2} )?(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sept?|Oct|Nov|Dec) (\d{4})\b/g;
  var NUM = /[−-]?₹?[−-]?\d+(?:,\d+)*(?:\.\d+)?%?/g;
  function hiDate(s) { return s.replace(DATE, function (m, d, mon, y) { return (d || '') + MONTHS[mon] + ' ' + y; }); }

  // Rules for sentences built from pieces (file names, several notes joined in one toast).
  var RULES = [
    [/^Categories for (\d+) SKUs? read from (.+?)\. Change any of them in the Costs tab\.?$/, function (m, n, f) { return f + ' से ' + n + ' SKU की कैटेगरी ली गई। लागत टैब में कोई भी बदल सकते हैं।'; }],
    [/^(.+) is already added\.?$/, function (m, f) { return f + ' पहले से जुड़ी है।'; }],
    [/^(.+) has no Excel or CSV files inside\.?$/, function (m, f) { return f + ' के अंदर कोई Excel या CSV फ़ाइल नहीं है।'; }],
    [/^(.+) is damaged or not a real ZIP file\. Download it again from Meesho\.?$/, function (m, f) { return f + ' खराब है या असली ZIP नहीं है। Meesho से दोबारा डाउनलोड करें।'; }],
    [/^(.+) is locked with a password\. Unzip it on your phone or computer first, then upload the Excel files\.?$/, function (m, f) { return f + ' पर पासवर्ड है। पहले इसे फ़ोन या कंप्यूटर पर अनज़िप करें, फिर Excel फ़ाइलें अपलोड करें।'; }],
    [/^(.+) is not an Excel, CSV or ZIP file\.?$/, function (m, f) { return f + ' Excel, CSV या ZIP फ़ाइल नहीं है।'; }],
    [/^(.+) could not be opened\. If it is password protected, open it in Excel and save a copy without a password\.?$/, function (m, f) { return f + ' खुल नहीं सकी। अगर पासवर्ड है तो Excel में खोलकर बिना पासवर्ड की कॉपी सेव करें।'; }],
    [/^(.+) has no Meesho payment, ads or order rows, and no SKU and Category columns\..*$/, function (m, f) { return f + ' में Meesho पेमेंट, विज्ञापन या ऑर्डर की लाइनें नहीं हैं, और SKU व Category कॉलम भी नहीं। पेमेंट रिपोर्ट (Excel), ऑर्डर CSV, या कैटेगरी वाली कैटलॉग फ़ाइल अपलोड करें।'; }],
    [/^(File added|(\d+) files added) from (.+)$/, function (m, a, n, z) { return z + ' से ' + (n ? n + ' फ़ाइलें जुड़ गईं' : 'फ़ाइल जुड़ गई'); }],
    [/^Automatic: your SKUs follow the letters rule \((\d+) of (\d+) combo names agree\)\..*$/, function (m, a, b) { return 'अपने आप: आपके SKU अक्षरों वाले नियम पर चलते हैं (' + b + ' में से ' + a + ' कॉम्बो नाम मेल खाते हैं)। अगर प्रोडक्ट के नाम में साइज़ लिखा है ("Pack of 3"), तो वही लिया जाता है। नहीं तो SKU में नंबर से पहले का हर अक्षर एक पीस है और ब्रैकेट में लिखा रंग एक और पीस (BPYG05 = 4, PGWM(GREY)05 = 5, G21 = 1); नंबर गिना नहीं जाता। जो SKU अलग हो, उसके लिए "पीस" में सही गिनती लिखें।'; }],
    [/^Saved (.+)$/, function (m, f) { return f + ' सेव हो गई'; }],
    [/^Undone: (.+)$/, function (m, f) { return 'वापस लिया: ' + f; }],
    [/^(.+), (.+ to .+), counted by payment date$/, function (m, b, p) { return b + ', ' + tr(p) + ', पेमेंट की तारीख से गिना'; }],
    [/^(.+), (.+ to .+), counted by order date$/, function (m, b, p) { return b + ', ' + tr(p) + ', ऑर्डर की तारीख से गिना'; }]
  ];

  // English text -> Hindi. Leading and trailing spaces are kept.
  function tr(s) {
    if (!s || !/[A-Za-z]/.test(s)) return s;
    var m = /^(\s*)([\s\S]*?)(\s*)$/.exec(s), core = m[2].replace(/\s+/g, ' ');
    var out = look(core);
    if (out == null) {
      // several sentences in one message: translate each
      var parts = core.replace(/\.\s+(?=[A-Z0-9])/g, '.\u0001').split('\u0001');
      if (parts.length > 1) {
        var done = parts.map(function (p) { var x = look(p); return x == null ? look(p.replace(/\.$/, '')) : x; });
        if (done.every(function (x) { return x != null; })) out = done.join(' ');
      }
    }
    if (out == null) out = hiDate(core);
    return out === core ? s : m[1] + out + m[3];
  }
  function look(core) {
    if (D[core]) return D[core];
    var nums = [], dates = [];
    var t = core.replace(DATE, function (x) { dates.push(hiDate(x)); return '{d}'; });
    t = t.replace(NUM, function (x, i, all) { if (i > 0 && /[A-Za-z\d{]/.test(all.charAt(i - 1))) return x; nums.push(x); return '{n}'; });
    if (D[t] != null) {
      var ni = 0, di = 0;
      return D[t].replace(/\{(n|d)(\d*)\}/g, function (x, k, i) {
        if (k === 'n') return i ? (nums[i - 1] || '') : (nums[ni++] || '');
        return i ? (dates[i - 1] || '') : (dates[di++] || '');
      });
    }
    for (var r = 0; r < RULES.length; r++) if (RULES[r][0].test(core)) return core.replace(RULES[r][0], RULES[r][1]);
    return null;
  }

  // Whole sentences with markup, where Hindi needs a different word order.
  var HTML = {
    'up.pay': 'Meesho सप्लायर पैनल में <strong>Payments</strong> खोलें और जिन तारीखों की चाहिए उनकी पेमेंट रिपोर्ट डाउनलोड करें। यह Excel फ़ाइल होती है जिसमें Order Payments और Ads Cost जैसी शीट होती हैं। जितनी पेमेंट फ़ाइलें हैं सब जोड़ें; दोहराई गई लाइनें एक ही बार गिनी जाती हैं।',
    'up.ord': '<strong>Orders</strong> में जाकर ऑर्डर CSV डाउनलोड करें। इससे वे ऑर्डर भी जुड़ते हैं जिनका पेमेंट अभी नहीं आया, ताकि बाकी और देर वाले पेमेंट दिखें।'
  };
  window.HI18N = { tr: tr, dict: D, html: HTML };
})();
